# docker-compose.yml

version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  testdb:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - postgres_testdata:/var/lib/postgresql/data

  app:
    image: node:18
    env_file:
      - docker.env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    working_dir: /app
    command: sh -c "npm start"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:
  postgres_testdata: